# Pytorch Tensors

A tensor is a n-dimensional matrix of only one data type. 
For example: 32-bit floating point, 32-bit complex, 32-bit integer (signed), Boolean...
A Tensor doesn't know anything about neural networks.


### References
[links](https://pytorch.org/docs/stable/tensors.html)

### Tensors vs numpy arrays vs lists (??)

Warning: Isn't a smart idea using lists in ML!
Numpy may not be the smartest idea for ML, it is designed for fast computations. 
It can be used for ML when combined with a ML package.

One of the main differences between a numpy array and a Pytorch tensor is that a pytorch is specifically tailored for GPU.

In [1]:
import torch
import numpy as np

x = torch.zeros(1,4)
y = np.zeros(4)
z = [0.]*4

print(x)
print(y)
print(z)

tensor([[0., 0., 0., 0.]])
[0. 0. 0. 0.]
[0.0, 0.0, 0.0, 0.0]


In [2]:
from sys import getsizeof


print(f'Size of the tensor is {getsizeof(x)} bytes')
print(f'Size of the numpy array is {getsizeof(y)} bytes')
print(f'Size of the list is {getsizeof(z)} bytes')


Size of the tensor is 72 bytes
Size of the numpy array is 144 bytes
Size of the list is 88 bytes


Data from a numpy array can be loaded/converted to a torch tensor and vice versa

In [3]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [4]:
y = torch.from_numpy(x)
y

tensor([1, 2, 3, 4, 5, 6])

In [5]:
z = y.numpy()
z

array([1, 2, 3, 4, 5, 6])

Also, we can load data from a list to a torch tensor

In [6]:
t = [1,2,3,4,5,6]
t

[1, 2, 3, 4, 5, 6]

In [7]:
x = torch.tensor(t)
x

tensor([1, 2, 3, 4, 5, 6])

As we mentioned before, we can run a tensor either on CPU or GPU. A quite handy method for choosing GPU over CPU is

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

We can also hardcode an option

In [9]:
device = torch.device('cpu')
device

device(type='cpu')