# Pytorch Tensors

A tensor is a data structure, a n-dimensional matrix of only one data type. 
For example: 32-bit floating point, 32-bit complex, 32-bit integer (signed), Boolean...
A Tensor doesn't know anything about neural networks, it is used to encode inputs, outputs and parameters of a model.

### References
[links](https://pytorch.org/docs/stable/tensors.html)

### Tensors vs numpy arrays vs lists (??)

Warning: Isn't a smart idea using lists in ML!
Numpy may not be the smartest idea for ML, it is designed for fast computations. 
It can be used for ML when combined with a ML package.

One of the main differences between a numpy array and a Pytorch tensor is that a pytorch is specifically tailored for GPU.


In [1]:
import torch
import numpy as np

x = torch.zeros(1,4)
y = np.zeros(4)
z = [0.]*4

print(x)
print(y)
print(z)

tensor([[0., 0., 0., 0.]])
[0. 0. 0. 0.]
[0.0, 0.0, 0.0, 0.0]


In [2]:
from sys import getsizeof


print(f'Size of the tensor is {getsizeof(x)} bytes')
print(f'Size of the numpy array is {getsizeof(y)} bytes')
print(f'Size of the list is {getsizeof(z)} bytes')


Size of the tensor is 72 bytes
Size of the numpy array is 144 bytes
Size of the list is 88 bytes


Data from a numpy array can be loaded/converted to a torch tensor and vice versa

In [3]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [4]:
y = torch.from_numpy(x)
y

tensor([1, 2, 3, 4, 5, 6])

It's important to note that if we change the x (numpy array) value here, we are also changing the y (tensor) value.

In [5]:
print(f'numpy array value = {x}')
print(f'tensor value = {y}')
x+=1
print(f'numpy array value after adding one to each array element = {x}')
print(f'current tensor value = {y}')


numpy array value = [1 2 3 4 5 6]
tensor value = tensor([1, 2, 3, 4, 5, 6])
numpy array value after adding one to each array element = [2 3 4 5 6 7]
current tensor value = tensor([2, 3, 4, 5, 6, 7])


In [6]:
z = y.numpy()
z

array([2, 3, 4, 5, 6, 7])

As we mentioned in the beginning of the chapter, we can run a tensor either on CPU or GPU. A quite handy method for choosing GPU over CPU is

In [7]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

If we want to send a tensor from CPU to GPU we must use the to() method

In [8]:
x = torch.ones(4)
x = x.to(device)
x

tensor([1., 1., 1., 1.], device='cuda:0')

We can also create a tensor in GPU. The main advantage of using GPU is to speed up ML operations

In [9]:
x = torch.ones(4,device=device)
x

tensor([1., 1., 1., 1.], device='cuda:0')

Once we create a tensor in GPU we can't use the numpy() method. Numpy can only handle CPU tensors.

In [10]:
try:
    x = x.numpy()
except TypeError:
    print('Ops, you should use Tensor.cpu()')

Ops, you should use Tensor.cpu()


Also, we can load data from a list to a torch tensor

In [11]:
t = [1,2,3,4,5,6]
t

[1, 2, 3, 4, 5, 6]

In [12]:
x = torch.tensor(t)
x

tensor([1, 2, 3, 4, 5, 6])

All tensors presented above are 1-dimensional, it is usualy called a vector.
A 2-dimensional tensor is sometimes referred as a matrix.

Sometimes is important to create a n-dimentional tensor with rand values.
And using torch this is really easy!
We can create using uniform distribution (rand) or normal distribution(randn).

In [13]:

x = torch.rand(2,2)

shape = (2,2)
y = torch.rand(shape)
print('x', x)
print('y', y)

x tensor([[0.0753, 0.5441],
        [0.8994, 0.5197]])
y tensor([[0.1709, 0.5705],
        [0.8628, 0.0363]])


If we execute the code above again, we will have different tensor's values.
In this sense, is important to set a seed to be able to reproduce the code.


In [14]:
print('\nset seed\n')

torch.manual_seed(1)

x = torch.rand(2,2)
shape = (2,2)
y = torch.rand(shape)
print('x', x)
print('y', y)

print('\nset seed again\n')
torch.manual_seed(1)

x = torch.rand(2,2)
shape = (2,2)
y = torch.rand(shape)
print('x', x)
print('y', y)


set seed

x tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])
y tensor([[0.0293, 0.7999],
        [0.3971, 0.7544]])

set seed again

x tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])
y tensor([[0.0293, 0.7999],
        [0.3971, 0.7544]])


To create a tensor with a specific data type we should set it as follows:

In [15]:
x = torch.ones(2,2,dtype= torch.float16)
print(x)
x = torch.ones(2,2,dtype= torch.int)
print(x)


tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


## Math and Tensors

Manipulating tensors is an usual task when working with Pytorch.
There are over 100 operations described in the [documentation](https://pytorch.org/docs/stable/torch.html).



For example, we can create two 1D tensor using 'arange', and apply operations such as multiply, sum...

In [16]:
x = torch.arange(0,3)
x

tensor([0, 1, 2])

In [17]:
y = torch.arange(1,4)
y

tensor([1, 2, 3])

We can element wise addition using '+' or torch.add()

In [18]:
print(x+y)
print(torch.add(x,y))


tensor([1, 3, 5])
tensor([1, 3, 5])


The same reasoning can be applied to other operations

In [19]:
print(x*y)
print(torch.mul(x,y))

tensor([0, 2, 6])
tensor([0, 2, 6])


In [20]:
z = x/y
print(z)
z = torch.div(x,y)
print(z)

tensor([0.0000, 0.5000, 0.6667])
tensor([0.0000, 0.5000, 0.6667])


We can also do inplace operations, i.e. modify the variable

In [21]:
print('x = ', x)
print('y = ', y)
y.add_(x)
print('new y = ', y)


x =  tensor([0, 1, 2])
y =  tensor([1, 2, 3])
new y =  tensor([1, 3, 5])


If the tensor is of floats or complex dtypes, we can use functions such as std, abs, sin, bitwise operations

In [22]:
torch.std(z)

tensor(0.3469)

In [23]:
x = torch.ones(2,2)
print('x',x)
y = torch.ones(2,2)
print('y',y)
z = x+y
print('z',z)
print('z**2',z**2)

x tensor([[1., 1.],
        [1., 1.]])
y tensor([[1., 1.],
        [1., 1.]])
z tensor([[2., 2.],
        [2., 2.]])
z**2 tensor([[4., 4.],
        [4., 4.]])


In [24]:
x = torch.tensor([1.,-2.,3.,-4.,5.,-6.])
print('Normal ',x)
x = torch.abs(x)
print('Abs ', x)
x = torch.tensor([1.9,-2.1,3.8,-4.2,5.7,-6.3])
print('Normal ',x)
x = torch.ceil(x)
print('Ceil ', x)


Normal  tensor([ 1., -2.,  3., -4.,  5., -6.])
Abs  tensor([1., 2., 3., 4., 5., 6.])
Normal  tensor([ 1.9000, -2.1000,  3.8000, -4.2000,  5.7000, -6.3000])
Ceil  tensor([ 2., -2.,  4., -4.,  6., -6.])


In [25]:
import math

x = torch.tensor([0, math.pi / 6,  math.pi / 2])
print('x', x)
y = torch.sin(x)
print('sin', y)

x tensor([0.0000, 0.5236, 1.5708])
sin tensor([0.0000, 0.5000, 1.0000])


We can also apply some lists functions


In [26]:
x = torch.ones(3,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

For example, we can set all elements from a specific row

In [27]:
x[0,:]=0
x

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
x[:,2]=0
x

tensor([[0., 0., 0.],
        [1., 1., 0.],
        [1., 1., 0.]])

We also can get a specific row or column

In [29]:
x[:,0]

tensor([0., 1., 1.])

In [30]:
x[0,:]

tensor([0., 0., 0.])

To access the value of a cell we can call the item() method. Observe the difference between using x[0][0] and x[0][0].item()

In [31]:
print(x)
print(x[0][0])
print(x[0][0].item())


tensor([[0., 0., 0.],
        [1., 1., 0.],
        [1., 1., 0.]])
tensor(0.)
0.0


### Reshape a tensor

we can reshape a tensor by calling the view method()
For example, if we have a 2x2 tensor, we can create a new 1x4 tensor.

In [32]:
x = torch.rand(2,2)
print(x)
print(f'len of x = {len(x)*len(x[0])}')
x = x.view(4)
print(x)
print(f'len of x after the reshape = {len(x)}')

tensor([[0.5695, 0.4388],
        [0.6387, 0.5247]])
len of x = 4
tensor([0.5695, 0.4388, 0.6387, 0.5247])
len of x after the reshape = 4


we can also let torch find the write size of a tensor after a reshape using [-1]. 
For example,
let x be a tensor of 8x8, using the vew() method we have

In [33]:
x = torch.rand(8,8)
print(x.size())

x = x.view(-1,16)
print(f'after the reshape the size of x is = {x.size()}')

torch.Size([8, 8])
after the reshape the size of x is = torch.Size([4, 16])
