# Pytorch Tensors

A tensor is a data structure, a n-dimensional matrix of only one data type. 
For example: 32-bit floating point, 32-bit complex, 32-bit integer (signed), Boolean...
A Tensor doesn't know anything about neural networks, it is used to encode inputs, outputs and parameters of a model.

### References
[links](https://pytorch.org/docs/stable/tensors.html)

### Tensors vs numpy arrays vs lists (??)

Warning: Isn't a smart idea using lists in ML!
Numpy may not be the smartest idea for ML, it is designed for fast computations. 
It can be used for ML when combined with a ML package.

One of the main differences between a numpy array and a Pytorch tensor is that a pytorch is specifically tailored for GPU.


In [1]:
import torch
import numpy as np

x = torch.zeros(1,4)
y = np.zeros(4)
z = [0.]*4

print(x)
print(y)
print(z)

tensor([[0., 0., 0., 0.]])
[0. 0. 0. 0.]
[0.0, 0.0, 0.0, 0.0]


In [2]:
from sys import getsizeof


print(f'Size of the tensor is {getsizeof(x)} bytes')
print(f'Size of the numpy array is {getsizeof(y)} bytes')
print(f'Size of the list is {getsizeof(z)} bytes')


Size of the tensor is 72 bytes
Size of the numpy array is 144 bytes
Size of the list is 88 bytes


Data from a numpy array can be loaded/converted to a torch tensor and vice versa

In [3]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [4]:
y = torch.from_numpy(x)
y

tensor([1, 2, 3, 4, 5, 6])

In [5]:
z = y.numpy()
z

array([1, 2, 3, 4, 5, 6])

Also, we can load data from a list to a torch tensor

In [6]:
t = [1,2,3,4,5,6]
t

[1, 2, 3, 4, 5, 6]

In [7]:
x = torch.tensor(t)
x

tensor([1, 2, 3, 4, 5, 6])

All tensors presented above are 1-dimensional, it is usualy called a vector.
A 2-dimensional tensor is sometimes referred as a matrix.

Sometimes is important to create a n-dimentional tensor with rand values.
And using torch this is really easy!

In [8]:

x = torch.rand(2,2)

shape = (2,2)
y = torch.rand(shape)
print('x', x)
print('y', y)

x tensor([[0.3866, 0.8059],
        [0.7353, 0.0772]])
y tensor([[0.0678, 0.9430],
        [0.3350, 0.7960]])


If we execute the code above again, we will have different tensor's values.
In this sense, is important to set a seed to be able to reproduce the code.


In [9]:
print('\nset seed\n')

torch.manual_seed(1)

x = torch.rand(2,2)
shape = (2,2)
y = torch.rand(shape)
print('x', x)
print('y', y)

print('\nset seed again\n')
torch.manual_seed(1)

x = torch.rand(2,2)
shape = (2,2)
y = torch.rand(shape)
print('x', x)
print('y', y)


set seed

x tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])
y tensor([[0.0293, 0.7999],
        [0.3971, 0.7544]])

set seed again

x tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])
y tensor([[0.0293, 0.7999],
        [0.3971, 0.7544]])


## Math and Tensors

Manipulating tensors is an usual task when working with Pytorch.
There are over 100 operations described in the [documentation](https://pytorch.org/docs/stable/torch.html).



For example, we can create two 1D tensor using 'arange', and apply operations such as multiply, sum...

In [10]:
x = torch.arange(0,3)
x

tensor([0, 1, 2])

In [11]:
y = torch.arange(1,4)
y

tensor([1, 2, 3])

In [12]:
x*y

tensor([0, 2, 6])

In [13]:
x+y

tensor([1, 3, 5])

In [14]:
z = x/y
z

tensor([0.0000, 0.5000, 0.6667])

If the tensor is of floats or complex dtypes, we can use functions such as std, abs, sin, bitwise operations

In [15]:
torch.std(z)

tensor(0.3469)

In [22]:
x = torch.ones(2,2)
print('x',x)
y = torch.ones(2,2)
print('y',y)
z = x+y
print('z',z)
print('z**2',z**2)

x tensor([[1., 1.],
        [1., 1.]])
y tensor([[1., 1.],
        [1., 1.]])
z tensor([[2., 2.],
        [2., 2.]])
z**2 tensor([[4., 4.],
        [4., 4.]])


In [30]:
x = torch.tensor([1.,-2.,3.,-4.,5.,-6.])
print('Normal ',x)
x = torch.abs(x)
print('Abs ', x)
x = torch.tensor([1.9,-2.1,3.8,-4.2,5.7,-6.3])
print('Normal ',x)
x = torch.ceil(x)
print('Ceil ', x)


Normal  tensor([ 1., -2.,  3., -4.,  5., -6.])
Abs  tensor([1., 2., 3., 4., 5., 6.])
Normal  tensor([ 1.9000, -2.1000,  3.8000, -4.2000,  5.7000, -6.3000])
Ceil  tensor([ 2., -2.,  4., -4.,  6., -6.])


In [34]:
import math

x = torch.tensor([0, math.pi / 6,  math.pi / 2])
print('x', x)
y = torch.sin(x)
print('sin', y)

x tensor([0.0000, 0.5236, 1.5708])
sin tensor([0.0000, 0.5000, 1.0000])


We can also apply some lists functions


In [ ]:
x = torch.ones(3,3)
x

In [ ]:
x[0,:]=0
x

In [ ]:
x[:,2]=0
x

As we mentioned in the beginning of the chapter, we can run a tensor either on CPU or GPU. A quite handy method for choosing GPU over CPU is

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

tensor([[ 0.1449, -0.0040,  0.8742,  0.3112],
        [-0.3724, -0.6040, -0.1676, -0.4313]])

tensor([[0.1449, 0.0040, 0.8742, 0.3112],
        [0.3724, 0.6040, 0.1676, 0.4313]])


tensor([[1., -0., 1., 1.],
        [-0., -0., -0., -0.]])
