# Pytorch Tensors

A tensor is a data structure, a n-dimensional matrix of only one data type. 
For example: 32-bit floating point, 32-bit complex, 32-bit integer (signed), Boolean...
A Tensor doesn't know anything about neural networks, it is used to encode inputs, outputs and parameters of a model.

### References
[links](https://pytorch.org/docs/stable/tensors.html)

### Tensors vs numpy arrays vs lists (??)

Warning: Isn't a smart idea using lists in ML!
Numpy may not be the smartest idea for ML, it is designed for fast computations. 
It can be used for ML when combined with a ML package.

One of the main differences between a numpy array and a Pytorch tensor is that a pytorch is specifically tailored for GPU.

In [1]:
import torch
import numpy as np

x = torch.zeros(1,4)
y = np.zeros(4)
z = [0.]*4

print(x)
print(y)
print(z)

tensor([[0., 0., 0., 0.]])
[0. 0. 0. 0.]
[0.0, 0.0, 0.0, 0.0]


In [2]:
from sys import getsizeof


print(f'Size of the tensor is {getsizeof(x)} bytes')
print(f'Size of the numpy array is {getsizeof(y)} bytes')
print(f'Size of the list is {getsizeof(z)} bytes')


Size of the tensor is 72 bytes
Size of the numpy array is 144 bytes
Size of the list is 88 bytes


Data from a numpy array can be loaded/converted to a torch tensor and vice versa

In [3]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [4]:
y = torch.from_numpy(x)
y

tensor([1, 2, 3, 4, 5, 6])

In [5]:
z = y.numpy()
z

array([1, 2, 3, 4, 5, 6])

Also, we can load data from a list to a torch tensor

In [6]:
t = [1,2,3,4,5,6]
t

[1, 2, 3, 4, 5, 6]

In [7]:
x = torch.tensor(t)
x

tensor([1, 2, 3, 4, 5, 6])

Sometimes is important to create a n-dimentional tensor with rand values.
And using torch this is really easy!

In [14]:

x = torch.rand(2,2)

shape = (2,2)
y = torch.rand(shape)
print('x', x)
print('y', y)

x tensor([[0.4931, 0.5235],
        [0.3360, 0.1025]])
y tensor([[0.8594, 0.3521],
        [0.6810, 0.6480]])


If we execute the code above again, we will have different tensor's values.
In this sense, is important to set a seed to be able to reproduce the code.


In [25]:
print('\nset seed\n')

torch.manual_seed(1)

x = torch.rand(2,2)
shape = (2,2)
y = torch.rand(shape)
print('x', x)
print('y', y)

print('\nset seed again\n')
torch.manual_seed(1)

x = torch.rand(2,2)
shape = (2,2)
y = torch.rand(shape)
print('x', x)
print('y', y)


set seed

x tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])
y tensor([[0.0293, 0.7999],
        [0.3971, 0.7544]])

set seed again

x tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])
y tensor([[0.0293, 0.7999],
        [0.3971, 0.7544]])



Manipulating tensors is an usual task when working with Pytorch.
There are over 100 operations described in the [documentation](https://pytorch.org/docs/stable/torch.html).



For example, we can create two 1D tensor using 'arange', and apply operations such as multiply, sum...

In [45]:
x = torch.arange(0,3)
x

tensor([0, 1, 2])

In [47]:
y = torch.arange(1,4)
y

tensor([1, 2, 3])

In [49]:
x*y

tensor([0, 2, 6])

In [50]:
x+y

tensor([1, 3, 5])

In [53]:
z = x/y
z

tensor([0.0000, 0.5000, 0.6667])

If the tensor is of floats or complex dtypes, we can use functions such as std

In [57]:
torch.std(z)

tensor(0.3469)

In [37]:
x = torch.ones(3,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [39]:
x[0,:]=0
x

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [44]:
x[:,2]=0
x

tensor([[0., 0., 0.],
        [1., 1., 0.],
        [1., 1., 0.]])

As we mentioned before, we can run a tensor either on CPU or GPU. A quite handy method for choosing GPU over CPU is

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

We can also hardcode an option

In [9]:
device = torch.device('cpu')
device

device(type='cpu')